autoDetectedPackages:
- com.jt808.common
- com.jt808.protocol.codec
- com.jt808.protocol.message
- com.jt808.server
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
startOnDebug: false
